config/routes.rb
Rails.application.routes.draw do

    resources :restaurants do
      resources :reviews, only: [ :new, :create ]
    end


  end
  # For details on the available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, :inclusion => {:in =>["chinese", "italian", "japanese", "french", "belgian"]}


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true, numericality: true, :inclusion => {:in=>0..5}
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :rating]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews = @restaurant.reviews
  end

  def new
   @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
     redirect_to restaurant_path(@restaurant)
    else
     render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_url, notice: 'Restaurant was successully destroyed.'}
      format.json { head :no_content }
    end
  end


  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
    redirect_to restaurant_path(@restaurant)
    else
    render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA_Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>

    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1 class="text-center">Restaurants</h1>
<ul>
  <% @restaurants.each do |a| %>
  <li><strong> Name: </strong>  <%=  a[:name]  %>
    <strong> Address: </strong>  <%= a[:address] %>
    <strong>Category:</strong>  <%= a[:category] %>
    <strong> Phone Number: </strong><%= a[:phone_number] %>
     <%= link_to "See Details", restaurant_path(a[:id]) %></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Restaurants</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<div class="text-center">
  <h4><%= @restaurant[:name]%></h4>
  <h3>Address: <%= @restaurant[:address] %> </h3>
  <h3>Category: <%= @restaurant[:category] %> </h3>
  <h3>Review: <%= @restaurant.reviews %> </h3>
  <h5><%= link_to "Add a review", new_restaurant_review_path(@restaurant[:id]) %></h5>
</div>

app/views/reviews/new.html.erb
  <h1>Review for <%= @restaurant.name %></h1>
   <%= simple_form_for [@restaurant, @review] do |f| %>
     <%= f.input :content %>
     <%= f.input :rating %>
     <%= f.submit class: "btn btn-primary"  %>
   <% end %>
  <%= link_to 'Back', restaurants_path %>